version: '3.8'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx:/etc/nginx"
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - "8000:8000"
      - "27017:27017"
    volumes:
      - "./api:/api"
    command: "python manage.py runserver 0.0.0.0:8000"
    depends_on: 
      - db
  gui:
    build: ./gui
    ports:
      - "8080:8080"
    volumes:
      - "./gui:/gui"
    depends_on:
      - api
    environment:
      CHOKIDAR_USEPOLLING: 'true'
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/var/lib/postgresql/data
