# Generated by Django 3.1.2 on 2020-11-02 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('util', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('utapmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='util.utapmodel')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
            bases=('util.utapmodel',),
        ),
    ]
