# Generated by Django 3.1 on 2020-09-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_test_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='steps',
            field=models.CharField(default='', max_length=36000),
        ),
    ]
