# Generated by Django 3.1 on 2020-09-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='steps',
            field=models.TextField(default='', max_length=36000),
        ),
    ]
